### PR TITLE
update motor controller functions

### PR DESCRIPTION
**Pull request by generationmake**
for a smoother ride

### CODE REVIEW

**Review by aentinger — COMMENTED** [review]
LGTM :+1: Probably we should test it on the real hardware. Also I'd delete any out-commented code.

**Comment by generationmake** [comment]
just tell me if it works and then i will clean up the code.

**Comment by aentinger** [comment]
It does not work, motors go immediately full speed after receiving a non-zero setpoint.

Thanks for the UF2 file, the next time just post it in the pull request (instead of adding it to the GitHub history).

**Comment by generationmake** [comment]
please exchange encoder connection

**Comment by aentinger** [comment]
I did exchange the encoder connection. The ramp-up is much smoother, however the ramp down is also much smoother. At a setpoint of 0 RPM I would expect the robot to stop immediately (or at least faster than it does now).

**Comment by generationmake** [comment]
Hi @aentinger 
please test again ;-)
[CyphalRobotController07-CAN-firmware.ino.uf2.zip](https://github.com/107-systems/CyphalRobotController07-CAN-firmware/files/13982969/CyphalRobotController07-CAN-firmware.ino.uf2.zip)

**Comment by aentinger** [comment]
I can confirm that both instant stopping at a 0 RPM set-point as well as re-setting the controller upon activated emergency switch works :+1: . I strongly suggest merging this PR and opening a new PR for the next feature (whatever that may be).

**Review by aentinger — APPROVED** [review]
LGTM :+1: good work @generationmake

**Pull request merged**
